<?php

namespace App\Imports;

use App\Models\Books;
use App\Models\BookVarient;
use App\Models\Category;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

use Maatwebsite\Excel\Concerns\ToCollection;

class ImportBooks implements ToCollection
{
    private int $totalRecords = 0;
    private int $successfullyImported = 0;
    private int $skipped = 0;
    private int $existingSku = 0;
    private int $excelDuplicateSku = 0;
    private int $invalidSku = 0;
    private int $otherValidationIssue = 0;
    private int $autoGeneratedSku = 0;
    private array $excelSkus = [];
    private array $duplicateSkus = [];
    private array $existingSkus = [];
    private array $invalidSkus = [];
    private array $errors = [];
    private array $usedNumbers = [];
    private int $nextNumber = 100000001;
    public function __construct()
    {
        $this->loadExistingSkuNumbers();
    }
    public function collection(Collection $rows)
    {
        foreach ($rows as $key => $value) {

            $excelRowNumber = $key + 1;
            if ($this->isEmptyRow($value)) {
                continue;
            }
            if (isset($value[0]) && isset($value[1]) &&(trim((string) $value[0]) === 'Book Id' || trim((string) $value[1]) === 'Book Name')) {
                continue;
            }
            $this->totalRecords++;
            try {
                $this->processRow(
                    $value,
                    $excelRowNumber
                );
            } catch (\Throwable $e) {

                $this->skipped++;
                $this->otherValidationIssue++;
                $this->errors[] = [
                    'row'     => $excelRowNumber,
                    'reason'  => $e->getMessage(),
                ];
                Log::error(
                    'Book Excel Row Import Error',
                    [
                        'row'     => $excelRowNumber,
                        'message' => $e->getMessage(),
                        'file'    => $e->getFile(),
                        'line'    => $e->getLine(),
                    ]
                );
            }
        }
    }

    private function processRow($value, int $excelRowNumber)
    {
        
        if (!isset($value[1]) ||trim((string) $value[1]) === '' ) {
            $this->skipped++;
            $this->otherValidationIssue++;
            $this->errors[] = [
                'row'    => $excelRowNumber,
                'reason' => 'Book Name is empty',
            ];
            return;
        }

        $skuIndexes = [
            24,
            29,
            34,
            39,
            44,
        ];

        $rowSkus = [];
        foreach ($skuIndexes as $skuIndex) {
            $sku = $this->cleanSku(
                $value[$skuIndex] ?? null
            );
            if ($sku !== '') {
                $rowSkus[] = $sku;
            }
        }
        foreach ($rowSkus as $sku) {


            if (!$this->isValidSku($sku)) {

                $this->skipped++;

                $this->invalidSku++;

                $this->invalidSkus[] = $sku;

                $this->errors[] = [
                    'row'    => $excelRowNumber,
                    'sku'    => $sku,
                    'reason' => 'Invalid SKU format',
                ];

                return;
            }

            if ($this->skuExistsInDatabase($sku)) {

                $this->skipped++;

                $this->existingSku++;

                $this->existingSkus[] = $sku;

                $this->errors[] = [
                    'row'    => $excelRowNumber,
                    'sku'    => $sku,
                    'reason' => 'SKU already exists in database',
                ];

                return;
            }
            if ( isset( $this->excelSkus[strtoupper($sku)]  ) ) {

                $this->skipped++;
                $this->excelDuplicateSku++;
                $this->duplicateSkus[] = $sku;
                $this->errors[] = [
                    'row'    => $excelRowNumber,
                    'sku'    => $sku,
                    'reason' => 'Duplicate SKU in Excel',
                ];
                return;
            }
        }

        foreach ($rowSkus as $sku) {

            $this->excelSkus[
                strtoupper($sku)
            ] = true;
        }
        DB::beginTransaction();

        try {
            $main_category = Category::where('name',$value[2] ?? null )
                ->where('level', 1)
                ->first();
            $sub_category = Category::where(
                'name',
                $value[3] ?? null
            )
                ->where('level', 2)
                ->first();
            $child_category = Category::where(
                'name',
                $value[4] ?? null
            )
                ->where('level', 3)
                ->first();
            $original_price =
                (float) ($value[11] ?? 0);

            $selling_price =
                (float) ($value[12] ?? 0);
            $percent = 0;
            if ($original_price > 0) {

                $percent =
                    (
                        ($original_price - $selling_price)
                        * 100
                    )
                    /
                    $original_price;
            }
            $book_check = Books::where(
                'book_id',
                $value[0] ?? null
            )->first();
            if ($book_check) {

                $book_create =
                    Books::find($book_check->id);

            } else {

                $book_create =
                    new Books();
            }

            $book_create->name =
                $value[1] ?? null;

            $book_create->category_id =
                $main_category->id ?? 0;

            $book_create->subcategory_id =
                $sub_category->id ?? 0;

            $book_create->childcategory_id =
                $child_category->id ?? 0;

            $book_create->author =
                $value[5] ?? null;

            $book_create->title_long =
                $value[6] ?? null;

            $book_create->format =!empty($value[7]) ? trim($value[7]): null;

            $book_create->language =
                $value[8] ?? null;

            $book_create->isbn13 =
                $value[9] ?? null;

            $book_create->publisher =
                $value[10] ?? null;

            $book_create->original_price =
                $original_price;

            $book_create->selling_price =
                $selling_price;

            $book_create->url_slug =
                Str::slug(
                    ($value[1] ?? '') .
                    '-' .
                    ($value[8] ?? '')
                );

            $book_create->discount =
                number_format(
                    $percent,
                    2
                );

            $book_create->gst_charge =
                !empty($value[13])
                    ? $value[13]
                    : 0;

            $book_create->hsn_code =
                $value[14] ?? null;

            $book_create->listed_by =
                $value[15] ?? null;

            if (!empty($value[16])) {

                $book_create->date_published =
                    convertExcelDate(
                        $value[16]
                    );
            }

            $book_create->status =
                (
                    isset($value[19]) &&
                    $value[19] === 'Active'
                )
                    ? 2
                    : 0;


            $book_create->dimensions =
                $value[17] ?? null;

            $book_create->pages =
                $value[18] ?? null;
            $book_create->save();
            if (!$book_create->book_id) {

                $book_create->book_id =
                    '#UBRB' .
                    $book_create->id;

                $book_create->save();
            }

            $variantData = [

                [
                    'condition' => $value[20] ?? null,
                    'price'     => $value[21] ?? null,
                    'stock'     => $value[22] ?? null,
                    'weight'    => $value[23] ?? null,
                    'sku'       => $value[24] ?? null,
                ],

                [
                    'condition' => $value[25] ?? null,
                    'price'     => $value[26] ?? null,
                    'stock'     => $value[27] ?? null,
                    'weight'    => $value[28] ?? null,
                    'sku'       => $value[29] ?? null,
                ],

                [
                    'condition' => $value[30] ?? null,
                    'price'     => $value[31] ?? null,
                    'stock'     => $value[32] ?? null,
                    'weight'    => $value[33] ?? null,
                    'sku'       => $value[34] ?? null,
                ],

                [
                    'condition' => $value[35] ?? null,
                    'price'     => $value[36] ?? null,
                    'stock'     => $value[37] ?? null,
                    'weight'    => $value[38] ?? null,
                    'sku'       => $value[39] ?? null,
                ],

                [
                    'condition' => $value[40] ?? null,
                    'price'     => $value[41] ?? null,
                    'stock'     => $value[42] ?? null,
                    'weight'    => $value[43] ?? null,
                    'sku'       => $value[44] ?? null,
                ],

            ];

            foreach ($variantData as $variant) {

                if (
                    empty(
                        trim(
                            (string)
                            $variant['condition']
                        )
                    )
                ) {
                    continue;
                }

                $sku =
                    $this->cleanSku(
                        $variant['sku']
                    );

                if ($sku === '') {

                    $sku =
                        $this->generateNextSku();

                    $this->autoGeneratedSku++;
                }


                $variantModel =
                    BookVarient::where(
                        'book_id',
                        $book_create->id
                    )
                    ->where(
                        'bookconditions',
                        $variant['condition']
                    )
                    ->first();


                if (!$variantModel) {

                    $variantModel =
                        new BookVarient();
                }

                $variantModel->book_id =
                    $book_create->id;

                $variantModel->bookconditions =
                    $variant['condition'];

                $variantModel->price =
                    $variant['price'];

                $variantModel->stock =
                    $variant['stock'];

                $variantModel->book_weight =
                    $variant['weight'];

                $variantModel->sku_number =
                    $sku;

                $variantModel->save();
            }
            $hasVariants =
                BookVarient::where(
                    'book_id',
                    $book_create->id
                )->exists();


            if (!$hasVariants) {

                if (
                    empty(
                        trim(
                            (string)
                            $book_create->sku
                        )
                    )
                ) {

                    $bookSku =
                        $this->generateNextSku();

                    $book_create->sku =
                        $bookSku;

                    $book_create->save();

                    $this->autoGeneratedSku++;
                }
            }

            DB::commit();
            $this->successfullyImported++;


        } catch (\Throwable $e) {


            DB::rollBack();

            throw $e;
        }
    }


    private function loadExistingSkuNumbers()
    {
        

        Books::query()
            ->whereNotNull('sku')
            ->where('sku', '!=', '')
            ->pluck('sku')
            ->each(function ($sku) {

                $this->addExistingSkuNumber(
                    $sku
                );
            });
        BookVarient::query()
            ->whereNotNull('sku_number')
            ->where('sku_number', '!=', '')
            ->pluck('sku_number')
            ->each(function ($sku) {

                $this->addExistingSkuNumber(
                    $sku
                );
            });
    }

    private function addExistingSkuNumber($sku)
    {
        $sku =
            trim(
                (string) $sku
            );


        if (
            preg_match(
                '/^UDB-(\d+)$/i',
                $sku,
                $match
            )
        ) {

            $this->usedNumbers[] =
                (int) $match[1];
        }
    }

    private function generateNextSku(): string
    {
        

        while (
            in_array(
                $this->nextNumber,
                $this->usedNumbers,
                true
            )
        ) {

            $this->nextNumber++;
        }

        $sku =
            'UDB-' .
            str_pad(
                $this->nextNumber,
                9,
                '0',
                STR_PAD_LEFT
            );

        $this->usedNumbers[] =
            $this->nextNumber;

        $this->nextNumber++;


        return $sku;
    }


    private function skuExistsInDatabase(
        string $sku
    ): bool {

        return
            Books::where(
                'sku',
                $sku
            )->exists()

            ||

            BookVarient::where(
                'sku_number',
                $sku
            )->exists();
    }

    private function isValidSku(
        string $sku
    ): bool {

        return preg_match(
            '/^UDB-\d{9}$/i',
            $sku
        ) === 1;
    }
    private function cleanSku($sku): string
    {
        return strtoupper(
            trim(
                (string) $sku
            )
        );
    }


    private function isEmptyRow($row): bool
    {
        foreach ($row as $value) {

            if (
                trim(
                    (string) $value
                ) !== ''
            ) {

                return false;
            }
        }

        return true;
    }

    public function getSummary(): array
    {
        return [

            'total' =>
                $this->totalRecords,

            'successfully_imported' =>
                $this->successfullyImported,

            'skipped' =>
                $this->skipped,

            'existing_sku' =>
                $this->existingSku,

            'excel_duplicate_sku' =>
                $this->excelDuplicateSku,

            'invalid_sku' =>
                $this->invalidSku,

            'other_validation_issue' =>
                $this->otherValidationIssue,

            'auto_generated_sku' =>
                $this->autoGeneratedSku,

            'duplicate_skus' =>
                array_values(
                    array_unique(
                        $this->duplicateSkus
                    )
                ),

            'existing_skus' =>
                array_values(
                    array_unique(
                        $this->existingSkus
                    )
                ),

            'invalid_skus' =>
                array_values(
                    array_unique(
                        $this->invalidSkus
                    )
                ),

            'errors' =>
                $this->errors,
        ];
    }
}